//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUC_VU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHUC_VU()
        {
            this.TV_BAN_CHAP_HANH = new HashSet<TV_BAN_CHAP_HANH>();
        }
    
        public decimal MA_CHUC_VU { get; set; }
        public string TEN_CHUC_VU { get; set; }
        public decimal HE_SO_LUONG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TV_BAN_CHAP_HANH> TV_BAN_CHAP_HANH { get; set; }
    }
}
