//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEU_THU
    {
        public decimal MA_PHIEU_THU { get; set; }
        public System.DateTime NGAY_LAP_PHIEU_THU { get; set; }
        public string NOI_DUNG_PHIEU_THU { get; set; }
        public decimal SO_TIEN_THU { get; set; }
        public decimal MA_BCH { get; set; }
        public Nullable<decimal> MA_THANH_VIEN { get; set; }
    
        public virtual THANH_VIEN THANH_VIEN { get; set; }
        public virtual TV_BAN_CHAP_HANH TV_BAN_CHAP_HANH { get; set; }
    }
}
