//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANH_VIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THANH_VIEN()
        {
            this.CLBs = new HashSet<CLB>();
            this.PHIEU_THU = new HashSet<PHIEU_THU>();
            this.THANH_VIEN_CLB = new HashSet<THANH_VIEN_CLB>();
            this.HOP_THUONG_NIEN = new HashSet<HOP_THUONG_NIEN>();
            this.HOAT_DONG = new HashSet<HOAT_DONG>();
        }
    
        public decimal MA_THANH_VIEN { get; set; }
        public string HO { get; set; }
        public string TEN { get; set; }
        public Nullable<short> NGAY_SINH { get; set; }
        public Nullable<short> THANG_SINH { get; set; }
        public short NAM_SINH { get; set; }
        public string GIOI_TINH { get; set; }
        public string DIA_CHI { get; set; }
        public System.DateTime NGAY_THAM_GIA { get; set; }
        public decimal MA_KHU_PHO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLB> CLBs { get; set; }
        public virtual KHU_PHO KHU_PHO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEU_THU> PHIEU_THU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THANH_VIEN_CLB> THANH_VIEN_CLB { get; set; }
        public virtual TV_BAN_CHAP_HANH TV_BAN_CHAP_HANH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOP_THUONG_NIEN> HOP_THUONG_NIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOAT_DONG> HOAT_DONG { get; set; }
    }
}
