//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TV_BAN_CHAP_HANH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TV_BAN_CHAP_HANH()
        {
            this.PHIEU_CHI = new HashSet<PHIEU_CHI>();
            this.PHIEU_THU = new HashSet<PHIEU_THU>();
            this.HOP_BCH = new HashSet<HOP_BCH>();
        }
    
        public decimal MA_BCH { get; set; }
        public string DAN_TOC { get; set; }
        public string TON_GIAO { get; set; }
        public string NGHE_NGHIEP { get; set; }
        public string DON_VI_CONG_TAC { get; set; }
        public string TRINH_DO_HOC_VAN { get; set; }
        public string TRINH_DO_CHUYEN_MON { get; set; }
        public string TRINH_DO_LY_LUAN_CHINH_TRI { get; set; }
        public decimal LUONG { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string EMAIL { get; set; }
        public decimal MA_CHUC_VU { get; set; }
    
        public virtual CHUC_VU CHUC_VU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEU_CHI> PHIEU_CHI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEU_THU> PHIEU_THU { get; set; }
        public virtual THANH_VIEN THANH_VIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOP_BCH> HOP_BCH { get; set; }
    }
}
