//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHoiNguoiCaoTuoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLB()
        {
            this.THANH_VIEN_CLB = new HashSet<THANH_VIEN_CLB>();
        }
    
        public decimal MA_CLB { get; set; }
        public string TEN_CLB { get; set; }
        public System.DateTime NGAY_THANH_LAP_CLB { get; set; }
        public decimal MA_QUAN_LY { get; set; }
    
        public virtual THANH_VIEN THANH_VIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THANH_VIEN_CLB> THANH_VIEN_CLB { get; set; }
    }
}
