//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHoiNguoiCaoTuoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class DON_VI_DONG_GOP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DON_VI_DONG_GOP()
        {
            this.PHIEU_DONG_GOP = new HashSet<PHIEU_DONG_GOP>();
        }
    
        public decimal MA_DON_VI { get; set; }
        public string TEN_DON_VI { get; set; }
        public string DIA_CHI { get; set; }
        public string EMAIL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEU_DONG_GOP> PHIEU_DONG_GOP { get; set; }
    }
}
