//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHoiNguoiCaoTuoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOAT_DONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOAT_DONG()
        {
            this.PHIEU_CHI = new HashSet<PHIEU_CHI>();
            this.THANH_VIEN = new HashSet<THANH_VIEN>();
        }
    
        public decimal MA_HOAT_DONG { get; set; }
        public string NOI_DUNG_HOAT_DONG { get; set; }
        public System.DateTime NGAY_BAT_DAU { get; set; }
        public System.DateTime NGAY_KET_THUC { get; set; }
        public byte DIEM_TOI_DA { get; set; }
        public Nullable<byte> DIEM_DAT_DUOC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEU_CHI> PHIEU_CHI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THANH_VIEN> THANH_VIEN { get; set; }
    }
}
