//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHoiNguoiCaoTuoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOP_THUONG_NIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOP_THUONG_NIEN()
        {
            this.THANH_VIEN = new HashSet<THANH_VIEN>();
        }
    
        public decimal MA_CUOC_HOP_TN { get; set; }
        public System.DateTime NGAY_GIO_HOP { get; set; }
        public string NOI_DUNG_HOP { get; set; }
        public string DIA_DIEM_HOP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THANH_VIEN> THANH_VIEN { get; set; }
    }
}
