//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHoiNguoiCaoTuoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOP_BCH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOP_BCH()
        {
            this.TV_BAN_CHAP_HANH = new HashSet<TV_BAN_CHAP_HANH>();
        }
    
        public decimal MA_CUOC_HOP_BCH { get; set; }
        public System.DateTime NGAY_GIO_HOP { get; set; }
        public string NOI_DUNG_HOP { get; set; }
        public string DIA_DIEM_HOP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TV_BAN_CHAP_HANH> TV_BAN_CHAP_HANH { get; set; }
    }
}
