//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHoiNguoiCaoTuoi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CAI_DAT> CAI_DAT { get; set; }
        public virtual DbSet<CHUC_VU> CHUC_VU { get; set; }
        public virtual DbSet<CLB> CLBs { get; set; }
        public virtual DbSet<DON_VI_DONG_GOP> DON_VI_DONG_GOP { get; set; }
        public virtual DbSet<HOAT_DONG> HOAT_DONG { get; set; }
        public virtual DbSet<HOP_BCH> HOP_BCH { get; set; }
        public virtual DbSet<HOP_THUONG_NIEN> HOP_THUONG_NIEN { get; set; }
        public virtual DbSet<KHU_PHO> KHU_PHO { get; set; }
        public virtual DbSet<PHIEU_CHI> PHIEU_CHI { get; set; }
        public virtual DbSet<PHIEU_DONG_GOP> PHIEU_DONG_GOP { get; set; }
        public virtual DbSet<PHIEU_THU> PHIEU_THU { get; set; }
        public virtual DbSet<THANH_VIEN> THANH_VIEN { get; set; }
        public virtual DbSet<THANH_VIEN_CLB> THANH_VIEN_CLB { get; set; }
        public virtual DbSet<TV_BAN_CHAP_HANH> TV_BAN_CHAP_HANH { get; set; }
        public virtual DbSet<V_THONGKETHUCHI> V_THONGKETHUCHI { get; set; }
        public virtual DbSet<V_THONGKETIENDONGGOP> V_THONGKETIENDONGGOP { get; set; }
    
        public virtual int SP_AUTH_CHANGEEMAIL(Nullable<decimal> v_MA_BCH, string v_EMAIL)
        {
            var v_MA_BCHParameter = v_MA_BCH.HasValue ?
                new ObjectParameter("V_MA_BCH", v_MA_BCH) :
                new ObjectParameter("V_MA_BCH", typeof(decimal));
    
            var v_EMAILParameter = v_EMAIL != null ?
                new ObjectParameter("V_EMAIL", v_EMAIL) :
                new ObjectParameter("V_EMAIL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AUTH_CHANGEEMAIL", v_MA_BCHParameter, v_EMAILParameter);
        }
    
        public virtual int SP_AUTH_CHANGEPASSWORD(Nullable<decimal> v_MA_BCH, string v_PASSWORD)
        {
            var v_MA_BCHParameter = v_MA_BCH.HasValue ?
                new ObjectParameter("V_MA_BCH", v_MA_BCH) :
                new ObjectParameter("V_MA_BCH", typeof(decimal));
    
            var v_PASSWORDParameter = v_PASSWORD != null ?
                new ObjectParameter("V_PASSWORD", v_PASSWORD) :
                new ObjectParameter("V_PASSWORD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AUTH_CHANGEPASSWORD", v_MA_BCHParameter, v_PASSWORDParameter);
        }
    
        public virtual int SP_CAI_DAT_INSERT(string v_TEN_THAM_SO, string v_GIA_TRI)
        {
            var v_TEN_THAM_SOParameter = v_TEN_THAM_SO != null ?
                new ObjectParameter("V_TEN_THAM_SO", v_TEN_THAM_SO) :
                new ObjectParameter("V_TEN_THAM_SO", typeof(string));
    
            var v_GIA_TRIParameter = v_GIA_TRI != null ?
                new ObjectParameter("V_GIA_TRI", v_GIA_TRI) :
                new ObjectParameter("V_GIA_TRI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CAI_DAT_INSERT", v_TEN_THAM_SOParameter, v_GIA_TRIParameter);
        }
    
        public virtual int SP_CAI_DAT_UPDATE(string v_TEN_THAM_SO, string v_GIA_TRI)
        {
            var v_TEN_THAM_SOParameter = v_TEN_THAM_SO != null ?
                new ObjectParameter("V_TEN_THAM_SO", v_TEN_THAM_SO) :
                new ObjectParameter("V_TEN_THAM_SO", typeof(string));
    
            var v_GIA_TRIParameter = v_GIA_TRI != null ?
                new ObjectParameter("V_GIA_TRI", v_GIA_TRI) :
                new ObjectParameter("V_GIA_TRI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CAI_DAT_UPDATE", v_TEN_THAM_SOParameter, v_GIA_TRIParameter);
        }
    
        public virtual int SP_CHI_TIET_HOP_BCH_DELETE(Nullable<decimal> v_MA_CUOC_HOP_BCH, Nullable<decimal> v_MA_BCH)
        {
            var v_MA_CUOC_HOP_BCHParameter = v_MA_CUOC_HOP_BCH.HasValue ?
                new ObjectParameter("V_MA_CUOC_HOP_BCH", v_MA_CUOC_HOP_BCH) :
                new ObjectParameter("V_MA_CUOC_HOP_BCH", typeof(decimal));
    
            var v_MA_BCHParameter = v_MA_BCH.HasValue ?
                new ObjectParameter("V_MA_BCH", v_MA_BCH) :
                new ObjectParameter("V_MA_BCH", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CHI_TIET_HOP_BCH_DELETE", v_MA_CUOC_HOP_BCHParameter, v_MA_BCHParameter);
        }
    
        public virtual int SP_CHI_TIET_HOP_BCH_INSERT(Nullable<decimal> v_MA_CUOC_HOP_BCH, Nullable<decimal> v_MA_BCH)
        {
            var v_MA_CUOC_HOP_BCHParameter = v_MA_CUOC_HOP_BCH.HasValue ?
                new ObjectParameter("V_MA_CUOC_HOP_BCH", v_MA_CUOC_HOP_BCH) :
                new ObjectParameter("V_MA_CUOC_HOP_BCH", typeof(decimal));
    
            var v_MA_BCHParameter = v_MA_BCH.HasValue ?
                new ObjectParameter("V_MA_BCH", v_MA_BCH) :
                new ObjectParameter("V_MA_BCH", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CHI_TIET_HOP_BCH_INSERT", v_MA_CUOC_HOP_BCHParameter, v_MA_BCHParameter);
        }
    
        public virtual int SP_CHI_TIET_HOP_TN_DELETE(Nullable<decimal> v_MA_CUOC_HOP_TN, Nullable<decimal> v_MA_THANH_VIEN)
        {
            var v_MA_CUOC_HOP_TNParameter = v_MA_CUOC_HOP_TN.HasValue ?
                new ObjectParameter("V_MA_CUOC_HOP_TN", v_MA_CUOC_HOP_TN) :
                new ObjectParameter("V_MA_CUOC_HOP_TN", typeof(decimal));
    
            var v_MA_THANH_VIENParameter = v_MA_THANH_VIEN.HasValue ?
                new ObjectParameter("V_MA_THANH_VIEN", v_MA_THANH_VIEN) :
                new ObjectParameter("V_MA_THANH_VIEN", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CHI_TIET_HOP_TN_DELETE", v_MA_CUOC_HOP_TNParameter, v_MA_THANH_VIENParameter);
        }
    
        public virtual int SP_CHI_TIET_HOP_TN_INSERT(Nullable<decimal> v_MA_CUOC_HOP_TN, Nullable<decimal> v_MA_THANH_VIEN)
        {
            var v_MA_CUOC_HOP_TNParameter = v_MA_CUOC_HOP_TN.HasValue ?
                new ObjectParameter("V_MA_CUOC_HOP_TN", v_MA_CUOC_HOP_TN) :
                new ObjectParameter("V_MA_CUOC_HOP_TN", typeof(decimal));
    
            var v_MA_THANH_VIENParameter = v_MA_THANH_VIEN.HasValue ?
                new ObjectParameter("V_MA_THANH_VIEN", v_MA_THANH_VIEN) :
                new ObjectParameter("V_MA_THANH_VIEN", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CHI_TIET_HOP_TN_INSERT", v_MA_CUOC_HOP_TNParameter, v_MA_THANH_VIENParameter);
        }
    
        public virtual int SP_CHUC_VU_UPDATE(Nullable<decimal> v_MA_CHUC_VU, Nullable<decimal> v_HE_SO_LUONG)
        {
            var v_MA_CHUC_VUParameter = v_MA_CHUC_VU.HasValue ?
                new ObjectParameter("V_MA_CHUC_VU", v_MA_CHUC_VU) :
                new ObjectParameter("V_MA_CHUC_VU", typeof(decimal));
    
            var v_HE_SO_LUONGParameter = v_HE_SO_LUONG.HasValue ?
                new ObjectParameter("V_HE_SO_LUONG", v_HE_SO_LUONG) :
                new ObjectParameter("V_HE_SO_LUONG", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CHUC_VU_UPDATE", v_MA_CHUC_VUParameter, v_HE_SO_LUONGParameter);
        }
    
        public virtual int SP_CLB_DELETE(Nullable<decimal> v_MA_CLB)
        {
            var v_MA_CLBParameter = v_MA_CLB.HasValue ?
                new ObjectParameter("V_MA_CLB", v_MA_CLB) :
                new ObjectParameter("V_MA_CLB", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CLB_DELETE", v_MA_CLBParameter);
        }
    
        public virtual int SP_CLB_INSERT(string v_TEN_CLB, Nullable<System.DateTime> v_NGAY_THANH_LAP_CLB, Nullable<decimal> v_MA_QUAN_LY)
        {
            var v_TEN_CLBParameter = v_TEN_CLB != null ?
                new ObjectParameter("V_TEN_CLB", v_TEN_CLB) :
                new ObjectParameter("V_TEN_CLB", typeof(string));
    
            var v_NGAY_THANH_LAP_CLBParameter = v_NGAY_THANH_LAP_CLB.HasValue ?
                new ObjectParameter("V_NGAY_THANH_LAP_CLB", v_NGAY_THANH_LAP_CLB) :
                new ObjectParameter("V_NGAY_THANH_LAP_CLB", typeof(System.DateTime));
    
            var v_MA_QUAN_LYParameter = v_MA_QUAN_LY.HasValue ?
                new ObjectParameter("V_MA_QUAN_LY", v_MA_QUAN_LY) :
                new ObjectParameter("V_MA_QUAN_LY", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CLB_INSERT", v_TEN_CLBParameter, v_NGAY_THANH_LAP_CLBParameter, v_MA_QUAN_LYParameter);
        }
    
        public virtual int SP_CLB_UPDATE(Nullable<decimal> v_MA_CLB, string v_TEN_CLB, Nullable<System.DateTime> v_NGAY_THANH_LAP_CLB, Nullable<decimal> v_MA_QUAN_LY)
        {
            var v_MA_CLBParameter = v_MA_CLB.HasValue ?
                new ObjectParameter("V_MA_CLB", v_MA_CLB) :
                new ObjectParameter("V_MA_CLB", typeof(decimal));
    
            var v_TEN_CLBParameter = v_TEN_CLB != null ?
                new ObjectParameter("V_TEN_CLB", v_TEN_CLB) :
                new ObjectParameter("V_TEN_CLB", typeof(string));
    
            var v_NGAY_THANH_LAP_CLBParameter = v_NGAY_THANH_LAP_CLB.HasValue ?
                new ObjectParameter("V_NGAY_THANH_LAP_CLB", v_NGAY_THANH_LAP_CLB) :
                new ObjectParameter("V_NGAY_THANH_LAP_CLB", typeof(System.DateTime));
    
            var v_MA_QUAN_LYParameter = v_MA_QUAN_LY.HasValue ?
                new ObjectParameter("V_MA_QUAN_LY", v_MA_QUAN_LY) :
                new ObjectParameter("V_MA_QUAN_LY", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CLB_UPDATE", v_MA_CLBParameter, v_TEN_CLBParameter, v_NGAY_THANH_LAP_CLBParameter, v_MA_QUAN_LYParameter);
        }
    
        public virtual int SP_DON_VI_DONG_GOP_DELETE(Nullable<decimal> v_MA_DON_VI)
        {
            var v_MA_DON_VIParameter = v_MA_DON_VI.HasValue ?
                new ObjectParameter("V_MA_DON_VI", v_MA_DON_VI) :
                new ObjectParameter("V_MA_DON_VI", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DON_VI_DONG_GOP_DELETE", v_MA_DON_VIParameter);
        }
    
        public virtual int SP_DON_VI_DONG_GOP_INSERT(string v_TEN_DON_VI, string v_DIA_CHI, string v_EMAIL)
        {
            var v_TEN_DON_VIParameter = v_TEN_DON_VI != null ?
                new ObjectParameter("V_TEN_DON_VI", v_TEN_DON_VI) :
                new ObjectParameter("V_TEN_DON_VI", typeof(string));
    
            var v_DIA_CHIParameter = v_DIA_CHI != null ?
                new ObjectParameter("V_DIA_CHI", v_DIA_CHI) :
                new ObjectParameter("V_DIA_CHI", typeof(string));
    
            var v_EMAILParameter = v_EMAIL != null ?
                new ObjectParameter("V_EMAIL", v_EMAIL) :
                new ObjectParameter("V_EMAIL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DON_VI_DONG_GOP_INSERT", v_TEN_DON_VIParameter, v_DIA_CHIParameter, v_EMAILParameter);
        }
    
        public virtual int SP_DON_VI_DONG_GOP_UPDATE(Nullable<decimal> v_MA_DON_VI, string v_TEN_DON_VI, string v_DIA_CHI, string v_EMAIL)
        {
            var v_MA_DON_VIParameter = v_MA_DON_VI.HasValue ?
                new ObjectParameter("V_MA_DON_VI", v_MA_DON_VI) :
                new ObjectParameter("V_MA_DON_VI", typeof(decimal));
    
            var v_TEN_DON_VIParameter = v_TEN_DON_VI != null ?
                new ObjectParameter("V_TEN_DON_VI", v_TEN_DON_VI) :
                new ObjectParameter("V_TEN_DON_VI", typeof(string));
    
            var v_DIA_CHIParameter = v_DIA_CHI != null ?
                new ObjectParameter("V_DIA_CHI", v_DIA_CHI) :
                new ObjectParameter("V_DIA_CHI", typeof(string));
    
            var v_EMAILParameter = v_EMAIL != null ?
                new ObjectParameter("V_EMAIL", v_EMAIL) :
                new ObjectParameter("V_EMAIL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DON_VI_DONG_GOP_UPDATE", v_MA_DON_VIParameter, v_TEN_DON_VIParameter, v_DIA_CHIParameter, v_EMAILParameter);
        }
    
        public virtual int SP_HOAT_DONG_DELETE(Nullable<decimal> v_MA_HOAT_DONG)
        {
            var v_MA_HOAT_DONGParameter = v_MA_HOAT_DONG.HasValue ?
                new ObjectParameter("V_MA_HOAT_DONG", v_MA_HOAT_DONG) :
                new ObjectParameter("V_MA_HOAT_DONG", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_HOAT_DONG_DELETE", v_MA_HOAT_DONGParameter);
        }
    
        public virtual int SP_HOAT_DONG_INSERT(string v_NOI_DUNG_HOAT_DONG, Nullable<System.DateTime> v_NGAY_BAT_DAU, Nullable<System.DateTime> v_NGAY_KET_THUC, Nullable<decimal> v_DIEM_TOI_DA, Nullable<decimal> v_DIEM_DAT_DUOC)
        {
            var v_NOI_DUNG_HOAT_DONGParameter = v_NOI_DUNG_HOAT_DONG != null ?
                new ObjectParameter("V_NOI_DUNG_HOAT_DONG", v_NOI_DUNG_HOAT_DONG) :
                new ObjectParameter("V_NOI_DUNG_HOAT_DONG", typeof(string));
    
            var v_NGAY_BAT_DAUParameter = v_NGAY_BAT_DAU.HasValue ?
                new ObjectParameter("V_NGAY_BAT_DAU", v_NGAY_BAT_DAU) :
                new ObjectParameter("V_NGAY_BAT_DAU", typeof(System.DateTime));
    
            var v_NGAY_KET_THUCParameter = v_NGAY_KET_THUC.HasValue ?
                new ObjectParameter("V_NGAY_KET_THUC", v_NGAY_KET_THUC) :
                new ObjectParameter("V_NGAY_KET_THUC", typeof(System.DateTime));
    
            var v_DIEM_TOI_DAParameter = v_DIEM_TOI_DA.HasValue ?
                new ObjectParameter("V_DIEM_TOI_DA", v_DIEM_TOI_DA) :
                new ObjectParameter("V_DIEM_TOI_DA", typeof(decimal));
    
            var v_DIEM_DAT_DUOCParameter = v_DIEM_DAT_DUOC.HasValue ?
                new ObjectParameter("V_DIEM_DAT_DUOC", v_DIEM_DAT_DUOC) :
                new ObjectParameter("V_DIEM_DAT_DUOC", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_HOAT_DONG_INSERT", v_NOI_DUNG_HOAT_DONGParameter, v_NGAY_BAT_DAUParameter, v_NGAY_KET_THUCParameter, v_DIEM_TOI_DAParameter, v_DIEM_DAT_DUOCParameter);
        }
    
        public virtual int SP_HOAT_DONG_UPDATE(Nullable<decimal> v_MA_HOAT_DONG, string v_NOI_DUNG_HOAT_DONG, Nullable<System.DateTime> v_NGAY_BAT_DAU, Nullable<System.DateTime> v_NGAY_KET_THUC, Nullable<decimal> v_DIEM_TOI_DA, Nullable<decimal> v_DIEM_DAT_DUOC)
        {
            var v_MA_HOAT_DONGParameter = v_MA_HOAT_DONG.HasValue ?
                new ObjectParameter("V_MA_HOAT_DONG", v_MA_HOAT_DONG) :
                new ObjectParameter("V_MA_HOAT_DONG", typeof(decimal));
    
            var v_NOI_DUNG_HOAT_DONGParameter = v_NOI_DUNG_HOAT_DONG != null ?
                new ObjectParameter("V_NOI_DUNG_HOAT_DONG", v_NOI_DUNG_HOAT_DONG) :
                new ObjectParameter("V_NOI_DUNG_HOAT_DONG", typeof(string));
    
            var v_NGAY_BAT_DAUParameter = v_NGAY_BAT_DAU.HasValue ?
                new ObjectParameter("V_NGAY_BAT_DAU", v_NGAY_BAT_DAU) :
                new ObjectParameter("V_NGAY_BAT_DAU", typeof(System.DateTime));
    
            var v_NGAY_KET_THUCParameter = v_NGAY_KET_THUC.HasValue ?
                new ObjectParameter("V_NGAY_KET_THUC", v_NGAY_KET_THUC) :
                new ObjectParameter("V_NGAY_KET_THUC", typeof(System.DateTime));
    
            var v_DIEM_TOI_DAParameter = v_DIEM_TOI_DA.HasValue ?
                new ObjectParameter("V_DIEM_TOI_DA", v_DIEM_TOI_DA) :
                new ObjectParameter("V_DIEM_TOI_DA", typeof(decimal));
    
            var v_DIEM_DAT_DUOCParameter = v_DIEM_DAT_DUOC.HasValue ?
                new ObjectParameter("V_DIEM_DAT_DUOC", v_DIEM_DAT_DUOC) :
                new ObjectParameter("V_DIEM_DAT_DUOC", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_HOAT_DONG_UPDATE", v_MA_HOAT_DONGParameter, v_NOI_DUNG_HOAT_DONGParameter, v_NGAY_BAT_DAUParameter, v_NGAY_KET_THUCParameter, v_DIEM_TOI_DAParameter, v_DIEM_DAT_DUOCParameter);
        }
    
        public virtual int SP_HOP_BCH_DELETE(Nullable<decimal> v_MA_CUOC_HOP_BCH)
        {
            var v_MA_CUOC_HOP_BCHParameter = v_MA_CUOC_HOP_BCH.HasValue ?
                new ObjectParameter("V_MA_CUOC_HOP_BCH", v_MA_CUOC_HOP_BCH) :
                new ObjectParameter("V_MA_CUOC_HOP_BCH", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_HOP_BCH_DELETE", v_MA_CUOC_HOP_BCHParameter);
        }
    
        public virtual int SP_HOP_BCH_INSERT(Nullable<System.DateTime> v_NGAY_GIO_HOP, string v_NOI_DUNG_HOP, string v_DIA_DIEM_HOP)
        {
            var v_NGAY_GIO_HOPParameter = v_NGAY_GIO_HOP.HasValue ?
                new ObjectParameter("V_NGAY_GIO_HOP", v_NGAY_GIO_HOP) :
                new ObjectParameter("V_NGAY_GIO_HOP", typeof(System.DateTime));
    
            var v_NOI_DUNG_HOPParameter = v_NOI_DUNG_HOP != null ?
                new ObjectParameter("V_NOI_DUNG_HOP", v_NOI_DUNG_HOP) :
                new ObjectParameter("V_NOI_DUNG_HOP", typeof(string));
    
            var v_DIA_DIEM_HOPParameter = v_DIA_DIEM_HOP != null ?
                new ObjectParameter("V_DIA_DIEM_HOP", v_DIA_DIEM_HOP) :
                new ObjectParameter("V_DIA_DIEM_HOP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_HOP_BCH_INSERT", v_NGAY_GIO_HOPParameter, v_NOI_DUNG_HOPParameter, v_DIA_DIEM_HOPParameter);
        }
    
        public virtual int SP_HOP_BCH_UPDATE(Nullable<decimal> v_MA_CUOC_HOP_BCH, Nullable<System.DateTime> v_NGAY_GIO_HOP, string v_NOI_DUNG_HOP, string v_DIA_DIEM_HOP)
        {
            var v_MA_CUOC_HOP_BCHParameter = v_MA_CUOC_HOP_BCH.HasValue ?
                new ObjectParameter("V_MA_CUOC_HOP_BCH", v_MA_CUOC_HOP_BCH) :
                new ObjectParameter("V_MA_CUOC_HOP_BCH", typeof(decimal));
    
            var v_NGAY_GIO_HOPParameter = v_NGAY_GIO_HOP.HasValue ?
                new ObjectParameter("V_NGAY_GIO_HOP", v_NGAY_GIO_HOP) :
                new ObjectParameter("V_NGAY_GIO_HOP", typeof(System.DateTime));
    
            var v_NOI_DUNG_HOPParameter = v_NOI_DUNG_HOP != null ?
                new ObjectParameter("V_NOI_DUNG_HOP", v_NOI_DUNG_HOP) :
                new ObjectParameter("V_NOI_DUNG_HOP", typeof(string));
    
            var v_DIA_DIEM_HOPParameter = v_DIA_DIEM_HOP != null ?
                new ObjectParameter("V_DIA_DIEM_HOP", v_DIA_DIEM_HOP) :
                new ObjectParameter("V_DIA_DIEM_HOP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_HOP_BCH_UPDATE", v_MA_CUOC_HOP_BCHParameter, v_NGAY_GIO_HOPParameter, v_NOI_DUNG_HOPParameter, v_DIA_DIEM_HOPParameter);
        }
    
        public virtual int SP_HOP_THUONG_NIEN_DELETE(Nullable<decimal> v_MA_CUOC_HOP_TN)
        {
            var v_MA_CUOC_HOP_TNParameter = v_MA_CUOC_HOP_TN.HasValue ?
                new ObjectParameter("V_MA_CUOC_HOP_TN", v_MA_CUOC_HOP_TN) :
                new ObjectParameter("V_MA_CUOC_HOP_TN", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_HOP_THUONG_NIEN_DELETE", v_MA_CUOC_HOP_TNParameter);
        }
    
        public virtual int SP_HOP_THUONG_NIEN_INSERT(Nullable<System.DateTime> v_NGAY_GIO_HOP, string v_NOI_DUNG_HOP, string v_DIA_DIEM_HOP)
        {
            var v_NGAY_GIO_HOPParameter = v_NGAY_GIO_HOP.HasValue ?
                new ObjectParameter("V_NGAY_GIO_HOP", v_NGAY_GIO_HOP) :
                new ObjectParameter("V_NGAY_GIO_HOP", typeof(System.DateTime));
    
            var v_NOI_DUNG_HOPParameter = v_NOI_DUNG_HOP != null ?
                new ObjectParameter("V_NOI_DUNG_HOP", v_NOI_DUNG_HOP) :
                new ObjectParameter("V_NOI_DUNG_HOP", typeof(string));
    
            var v_DIA_DIEM_HOPParameter = v_DIA_DIEM_HOP != null ?
                new ObjectParameter("V_DIA_DIEM_HOP", v_DIA_DIEM_HOP) :
                new ObjectParameter("V_DIA_DIEM_HOP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_HOP_THUONG_NIEN_INSERT", v_NGAY_GIO_HOPParameter, v_NOI_DUNG_HOPParameter, v_DIA_DIEM_HOPParameter);
        }
    
        public virtual int SP_HOP_THUONG_NIEN_UPDATE(Nullable<decimal> v_MA_CUOC_HOP_TN, Nullable<System.DateTime> v_NGAY_GIO_HOP, string v_NOI_DUNG_HOP, string v_DIA_DIEM_HOP)
        {
            var v_MA_CUOC_HOP_TNParameter = v_MA_CUOC_HOP_TN.HasValue ?
                new ObjectParameter("V_MA_CUOC_HOP_TN", v_MA_CUOC_HOP_TN) :
                new ObjectParameter("V_MA_CUOC_HOP_TN", typeof(decimal));
    
            var v_NGAY_GIO_HOPParameter = v_NGAY_GIO_HOP.HasValue ?
                new ObjectParameter("V_NGAY_GIO_HOP", v_NGAY_GIO_HOP) :
                new ObjectParameter("V_NGAY_GIO_HOP", typeof(System.DateTime));
    
            var v_NOI_DUNG_HOPParameter = v_NOI_DUNG_HOP != null ?
                new ObjectParameter("V_NOI_DUNG_HOP", v_NOI_DUNG_HOP) :
                new ObjectParameter("V_NOI_DUNG_HOP", typeof(string));
    
            var v_DIA_DIEM_HOPParameter = v_DIA_DIEM_HOP != null ?
                new ObjectParameter("V_DIA_DIEM_HOP", v_DIA_DIEM_HOP) :
                new ObjectParameter("V_DIA_DIEM_HOP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_HOP_THUONG_NIEN_UPDATE", v_MA_CUOC_HOP_TNParameter, v_NGAY_GIO_HOPParameter, v_NOI_DUNG_HOPParameter, v_DIA_DIEM_HOPParameter);
        }
    
        public virtual int SP_KHU_PHO_DELETE(Nullable<decimal> v_MA_KHU_PHO)
        {
            var v_MA_KHU_PHOParameter = v_MA_KHU_PHO.HasValue ?
                new ObjectParameter("V_MA_KHU_PHO", v_MA_KHU_PHO) :
                new ObjectParameter("V_MA_KHU_PHO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_KHU_PHO_DELETE", v_MA_KHU_PHOParameter);
        }
    
        public virtual int SP_KHU_PHO_INSERT(string v_TEN_KHU_PHO)
        {
            var v_TEN_KHU_PHOParameter = v_TEN_KHU_PHO != null ?
                new ObjectParameter("V_TEN_KHU_PHO", v_TEN_KHU_PHO) :
                new ObjectParameter("V_TEN_KHU_PHO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_KHU_PHO_INSERT", v_TEN_KHU_PHOParameter);
        }
    
        public virtual int SP_KHU_PHO_UPDATE(Nullable<decimal> v_MA_KHU_PHO, string v_TEN_KHU_PHO)
        {
            var v_MA_KHU_PHOParameter = v_MA_KHU_PHO.HasValue ?
                new ObjectParameter("V_MA_KHU_PHO", v_MA_KHU_PHO) :
                new ObjectParameter("V_MA_KHU_PHO", typeof(decimal));
    
            var v_TEN_KHU_PHOParameter = v_TEN_KHU_PHO != null ?
                new ObjectParameter("V_TEN_KHU_PHO", v_TEN_KHU_PHO) :
                new ObjectParameter("V_TEN_KHU_PHO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_KHU_PHO_UPDATE", v_MA_KHU_PHOParameter, v_TEN_KHU_PHOParameter);
        }
    
        public virtual int SP_PHIEU_CHI_DELETE(Nullable<decimal> v_MA_PHIEU_CHI)
        {
            var v_MA_PHIEU_CHIParameter = v_MA_PHIEU_CHI.HasValue ?
                new ObjectParameter("V_MA_PHIEU_CHI", v_MA_PHIEU_CHI) :
                new ObjectParameter("V_MA_PHIEU_CHI", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PHIEU_CHI_DELETE", v_MA_PHIEU_CHIParameter);
        }
    
        public virtual int SP_PHIEU_CHI_DUYET(Nullable<decimal> v_MA_PHIEU_CHI, Nullable<System.DateTime> v_NGAY_DUYET)
        {
            var v_MA_PHIEU_CHIParameter = v_MA_PHIEU_CHI.HasValue ?
                new ObjectParameter("V_MA_PHIEU_CHI", v_MA_PHIEU_CHI) :
                new ObjectParameter("V_MA_PHIEU_CHI", typeof(decimal));
    
            var v_NGAY_DUYETParameter = v_NGAY_DUYET.HasValue ?
                new ObjectParameter("V_NGAY_DUYET", v_NGAY_DUYET) :
                new ObjectParameter("V_NGAY_DUYET", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PHIEU_CHI_DUYET", v_MA_PHIEU_CHIParameter, v_NGAY_DUYETParameter);
        }
    
        public virtual int SP_PHIEU_CHI_INSERT(Nullable<System.DateTime> v_NGAY_LAP_PHIEU_CHI, string v_NOI_DUNG_CHI, Nullable<decimal> v_SO_TIEN_CHI, Nullable<decimal> v_MA_HOAT_DONG, Nullable<decimal> v_MA_BCH)
        {
            var v_NGAY_LAP_PHIEU_CHIParameter = v_NGAY_LAP_PHIEU_CHI.HasValue ?
                new ObjectParameter("V_NGAY_LAP_PHIEU_CHI", v_NGAY_LAP_PHIEU_CHI) :
                new ObjectParameter("V_NGAY_LAP_PHIEU_CHI", typeof(System.DateTime));
    
            var v_NOI_DUNG_CHIParameter = v_NOI_DUNG_CHI != null ?
                new ObjectParameter("V_NOI_DUNG_CHI", v_NOI_DUNG_CHI) :
                new ObjectParameter("V_NOI_DUNG_CHI", typeof(string));
    
            var v_SO_TIEN_CHIParameter = v_SO_TIEN_CHI.HasValue ?
                new ObjectParameter("V_SO_TIEN_CHI", v_SO_TIEN_CHI) :
                new ObjectParameter("V_SO_TIEN_CHI", typeof(decimal));
    
            var v_MA_HOAT_DONGParameter = v_MA_HOAT_DONG.HasValue ?
                new ObjectParameter("V_MA_HOAT_DONG", v_MA_HOAT_DONG) :
                new ObjectParameter("V_MA_HOAT_DONG", typeof(decimal));
    
            var v_MA_BCHParameter = v_MA_BCH.HasValue ?
                new ObjectParameter("V_MA_BCH", v_MA_BCH) :
                new ObjectParameter("V_MA_BCH", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PHIEU_CHI_INSERT", v_NGAY_LAP_PHIEU_CHIParameter, v_NOI_DUNG_CHIParameter, v_SO_TIEN_CHIParameter, v_MA_HOAT_DONGParameter, v_MA_BCHParameter);
        }
    
        public virtual int SP_PHIEU_DONG_GOP_DELETE(Nullable<decimal> v_MA_PHIEU_DONG_GOP)
        {
            var v_MA_PHIEU_DONG_GOPParameter = v_MA_PHIEU_DONG_GOP.HasValue ?
                new ObjectParameter("V_MA_PHIEU_DONG_GOP", v_MA_PHIEU_DONG_GOP) :
                new ObjectParameter("V_MA_PHIEU_DONG_GOP", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PHIEU_DONG_GOP_DELETE", v_MA_PHIEU_DONG_GOPParameter);
        }
    
        public virtual int SP_PHIEU_DONG_GOP_INSERT(Nullable<System.DateTime> v_NGAY_DONG_GOP, Nullable<decimal> v_SO_TIEN_DONG_GOP, Nullable<decimal> v_MA_DON_VI)
        {
            var v_NGAY_DONG_GOPParameter = v_NGAY_DONG_GOP.HasValue ?
                new ObjectParameter("V_NGAY_DONG_GOP", v_NGAY_DONG_GOP) :
                new ObjectParameter("V_NGAY_DONG_GOP", typeof(System.DateTime));
    
            var v_SO_TIEN_DONG_GOPParameter = v_SO_TIEN_DONG_GOP.HasValue ?
                new ObjectParameter("V_SO_TIEN_DONG_GOP", v_SO_TIEN_DONG_GOP) :
                new ObjectParameter("V_SO_TIEN_DONG_GOP", typeof(decimal));
    
            var v_MA_DON_VIParameter = v_MA_DON_VI.HasValue ?
                new ObjectParameter("V_MA_DON_VI", v_MA_DON_VI) :
                new ObjectParameter("V_MA_DON_VI", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PHIEU_DONG_GOP_INSERT", v_NGAY_DONG_GOPParameter, v_SO_TIEN_DONG_GOPParameter, v_MA_DON_VIParameter);
        }
    
        public virtual int SP_PHIEU_DONG_GOP_UPDATE(Nullable<decimal> v_MA_PHIEU_DONG_GOP, Nullable<System.DateTime> v_NGAY_DONG_GOP, Nullable<decimal> v_SO_TIEN_DONG_GOP, Nullable<decimal> v_MA_DON_VI)
        {
            var v_MA_PHIEU_DONG_GOPParameter = v_MA_PHIEU_DONG_GOP.HasValue ?
                new ObjectParameter("V_MA_PHIEU_DONG_GOP", v_MA_PHIEU_DONG_GOP) :
                new ObjectParameter("V_MA_PHIEU_DONG_GOP", typeof(decimal));
    
            var v_NGAY_DONG_GOPParameter = v_NGAY_DONG_GOP.HasValue ?
                new ObjectParameter("V_NGAY_DONG_GOP", v_NGAY_DONG_GOP) :
                new ObjectParameter("V_NGAY_DONG_GOP", typeof(System.DateTime));
    
            var v_SO_TIEN_DONG_GOPParameter = v_SO_TIEN_DONG_GOP.HasValue ?
                new ObjectParameter("V_SO_TIEN_DONG_GOP", v_SO_TIEN_DONG_GOP) :
                new ObjectParameter("V_SO_TIEN_DONG_GOP", typeof(decimal));
    
            var v_MA_DON_VIParameter = v_MA_DON_VI.HasValue ?
                new ObjectParameter("V_MA_DON_VI", v_MA_DON_VI) :
                new ObjectParameter("V_MA_DON_VI", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PHIEU_DONG_GOP_UPDATE", v_MA_PHIEU_DONG_GOPParameter, v_NGAY_DONG_GOPParameter, v_SO_TIEN_DONG_GOPParameter, v_MA_DON_VIParameter);
        }
    
        public virtual int SP_PHIEU_THU_DELETE(Nullable<decimal> v_MA_PHIEU_THU)
        {
            var v_MA_PHIEU_THUParameter = v_MA_PHIEU_THU.HasValue ?
                new ObjectParameter("V_MA_PHIEU_THU", v_MA_PHIEU_THU) :
                new ObjectParameter("V_MA_PHIEU_THU", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PHIEU_THU_DELETE", v_MA_PHIEU_THUParameter);
        }
    
        public virtual int SP_PHIEU_THU_INSERT(Nullable<System.DateTime> v_NGAY_LAP_PHIEU_THU, string v_NOI_DUNG_PHIEU_THU, Nullable<decimal> v_SO_TIEN_THU, Nullable<decimal> v_MA_BCH, Nullable<decimal> v_MA_THANH_VIEN)
        {
            var v_NGAY_LAP_PHIEU_THUParameter = v_NGAY_LAP_PHIEU_THU.HasValue ?
                new ObjectParameter("V_NGAY_LAP_PHIEU_THU", v_NGAY_LAP_PHIEU_THU) :
                new ObjectParameter("V_NGAY_LAP_PHIEU_THU", typeof(System.DateTime));
    
            var v_NOI_DUNG_PHIEU_THUParameter = v_NOI_DUNG_PHIEU_THU != null ?
                new ObjectParameter("V_NOI_DUNG_PHIEU_THU", v_NOI_DUNG_PHIEU_THU) :
                new ObjectParameter("V_NOI_DUNG_PHIEU_THU", typeof(string));
    
            var v_SO_TIEN_THUParameter = v_SO_TIEN_THU.HasValue ?
                new ObjectParameter("V_SO_TIEN_THU", v_SO_TIEN_THU) :
                new ObjectParameter("V_SO_TIEN_THU", typeof(decimal));
    
            var v_MA_BCHParameter = v_MA_BCH.HasValue ?
                new ObjectParameter("V_MA_BCH", v_MA_BCH) :
                new ObjectParameter("V_MA_BCH", typeof(decimal));
    
            var v_MA_THANH_VIENParameter = v_MA_THANH_VIEN.HasValue ?
                new ObjectParameter("V_MA_THANH_VIEN", v_MA_THANH_VIEN) :
                new ObjectParameter("V_MA_THANH_VIEN", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PHIEU_THU_INSERT", v_NGAY_LAP_PHIEU_THUParameter, v_NOI_DUNG_PHIEU_THUParameter, v_SO_TIEN_THUParameter, v_MA_BCHParameter, v_MA_THANH_VIENParameter);
        }
    
        public virtual int SP_PKG_TIMKIEMDONVIDG_TIMTHEODIACHI(string dIACHI)
        {
            var dIACHIParameter = dIACHI != null ?
                new ObjectParameter("DIACHI", dIACHI) :
                new ObjectParameter("DIACHI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PKG_TIMKIEMDONVIDG_TIMTHEODIACHI", dIACHIParameter);
        }
    
        public virtual int SP_PKG_TIMKIEMDONVIDG_TIMTHEOEMAIL(string eMAIL)
        {
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PKG_TIMKIEMDONVIDG_TIMTHEOEMAIL", eMAILParameter);
        }
    
        public virtual int SP_PKG_TIMKIEMDONVIDG_TIMTHEOTEN(string tEN)
        {
            var tENParameter = tEN != null ?
                new ObjectParameter("TEN", tEN) :
                new ObjectParameter("TEN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PKG_TIMKIEMDONVIDG_TIMTHEOTEN", tENParameter);
        }
    
        public virtual int SP_PKG_TIMKIEMHOATDONG_TIMTHEONOIDUNG(string nD)
        {
            var nDParameter = nD != null ?
                new ObjectParameter("ND", nD) :
                new ObjectParameter("ND", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PKG_TIMKIEMHOATDONG_TIMTHEONOIDUNG", nDParameter);
        }
    
        public virtual int SP_PKG_TIMKIEMHOATDONG_TIMTHEOTHANGNAM(Nullable<decimal> m, Nullable<decimal> y)
        {
            var mParameter = m.HasValue ?
                new ObjectParameter("M", m) :
                new ObjectParameter("M", typeof(decimal));
    
            var yParameter = y.HasValue ?
                new ObjectParameter("Y", y) :
                new ObjectParameter("Y", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PKG_TIMKIEMHOATDONG_TIMTHEOTHANGNAM", mParameter, yParameter);
        }
    
        public virtual int SP_PKG_TIMKIEMTHANHVIEN_TIMTHEODIACHI(string dIACHI)
        {
            var dIACHIParameter = dIACHI != null ?
                new ObjectParameter("DIACHI", dIACHI) :
                new ObjectParameter("DIACHI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PKG_TIMKIEMTHANHVIEN_TIMTHEODIACHI", dIACHIParameter);
        }
    
        public virtual int SP_PKG_TIMKIEMTHANHVIEN_TIMTHEOHOTEN(string hO_TEN)
        {
            var hO_TENParameter = hO_TEN != null ?
                new ObjectParameter("HO_TEN", hO_TEN) :
                new ObjectParameter("HO_TEN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PKG_TIMKIEMTHANHVIEN_TIMTHEOHOTEN", hO_TENParameter);
        }
    
        public virtual int SP_PKG_TIMKIEMTHANHVIEN_TIMTHEONGAYTG(Nullable<System.DateTime> nGAYTG)
        {
            var nGAYTGParameter = nGAYTG.HasValue ?
                new ObjectParameter("NGAYTG", nGAYTG) :
                new ObjectParameter("NGAYTG", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PKG_TIMKIEMTHANHVIEN_TIMTHEONGAYTG", nGAYTGParameter);
        }
    
        public virtual int SP_THANH_VIEN_CLB_DELETE(Nullable<decimal> v_MA_CLB, Nullable<decimal> v_MA_THANH_VIEN)
        {
            var v_MA_CLBParameter = v_MA_CLB.HasValue ?
                new ObjectParameter("V_MA_CLB", v_MA_CLB) :
                new ObjectParameter("V_MA_CLB", typeof(decimal));
    
            var v_MA_THANH_VIENParameter = v_MA_THANH_VIEN.HasValue ?
                new ObjectParameter("V_MA_THANH_VIEN", v_MA_THANH_VIEN) :
                new ObjectParameter("V_MA_THANH_VIEN", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_THANH_VIEN_CLB_DELETE", v_MA_CLBParameter, v_MA_THANH_VIENParameter);
        }
    
        public virtual int SP_THANH_VIEN_CLB_INSERT(Nullable<decimal> v_MA_CLB, Nullable<decimal> v_MA_THANH_VIEN, Nullable<System.DateTime> v_NGAY_THAM_GIA_CLB)
        {
            var v_MA_CLBParameter = v_MA_CLB.HasValue ?
                new ObjectParameter("V_MA_CLB", v_MA_CLB) :
                new ObjectParameter("V_MA_CLB", typeof(decimal));
    
            var v_MA_THANH_VIENParameter = v_MA_THANH_VIEN.HasValue ?
                new ObjectParameter("V_MA_THANH_VIEN", v_MA_THANH_VIEN) :
                new ObjectParameter("V_MA_THANH_VIEN", typeof(decimal));
    
            var v_NGAY_THAM_GIA_CLBParameter = v_NGAY_THAM_GIA_CLB.HasValue ?
                new ObjectParameter("V_NGAY_THAM_GIA_CLB", v_NGAY_THAM_GIA_CLB) :
                new ObjectParameter("V_NGAY_THAM_GIA_CLB", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_THANH_VIEN_CLB_INSERT", v_MA_CLBParameter, v_MA_THANH_VIENParameter, v_NGAY_THAM_GIA_CLBParameter);
        }
    
        public virtual int SP_THANH_VIEN_DELETE(Nullable<decimal> v_MA_THANH_VIEN)
        {
            var v_MA_THANH_VIENParameter = v_MA_THANH_VIEN.HasValue ?
                new ObjectParameter("V_MA_THANH_VIEN", v_MA_THANH_VIEN) :
                new ObjectParameter("V_MA_THANH_VIEN", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_THANH_VIEN_DELETE", v_MA_THANH_VIENParameter);
        }
    
        public virtual int SP_THANH_VIEN_INSERT(string v_HO, string v_TEN, Nullable<decimal> v_NGAY_SINH, Nullable<decimal> v_THANG_SINH, Nullable<decimal> v_NAM_SINH, string v_GIOI_TINH, string v_DIA_CHI, Nullable<System.DateTime> v_NGAY_THAM_GIA, Nullable<decimal> v_MA_KHU_PHO)
        {
            var v_HOParameter = v_HO != null ?
                new ObjectParameter("V_HO", v_HO) :
                new ObjectParameter("V_HO", typeof(string));
    
            var v_TENParameter = v_TEN != null ?
                new ObjectParameter("V_TEN", v_TEN) :
                new ObjectParameter("V_TEN", typeof(string));
    
            var v_NGAY_SINHParameter = v_NGAY_SINH.HasValue ?
                new ObjectParameter("V_NGAY_SINH", v_NGAY_SINH) :
                new ObjectParameter("V_NGAY_SINH", typeof(decimal));
    
            var v_THANG_SINHParameter = v_THANG_SINH.HasValue ?
                new ObjectParameter("V_THANG_SINH", v_THANG_SINH) :
                new ObjectParameter("V_THANG_SINH", typeof(decimal));
    
            var v_NAM_SINHParameter = v_NAM_SINH.HasValue ?
                new ObjectParameter("V_NAM_SINH", v_NAM_SINH) :
                new ObjectParameter("V_NAM_SINH", typeof(decimal));
    
            var v_GIOI_TINHParameter = v_GIOI_TINH != null ?
                new ObjectParameter("V_GIOI_TINH", v_GIOI_TINH) :
                new ObjectParameter("V_GIOI_TINH", typeof(string));
    
            var v_DIA_CHIParameter = v_DIA_CHI != null ?
                new ObjectParameter("V_DIA_CHI", v_DIA_CHI) :
                new ObjectParameter("V_DIA_CHI", typeof(string));
    
            var v_NGAY_THAM_GIAParameter = v_NGAY_THAM_GIA.HasValue ?
                new ObjectParameter("V_NGAY_THAM_GIA", v_NGAY_THAM_GIA) :
                new ObjectParameter("V_NGAY_THAM_GIA", typeof(System.DateTime));
    
            var v_MA_KHU_PHOParameter = v_MA_KHU_PHO.HasValue ?
                new ObjectParameter("V_MA_KHU_PHO", v_MA_KHU_PHO) :
                new ObjectParameter("V_MA_KHU_PHO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_THANH_VIEN_INSERT", v_HOParameter, v_TENParameter, v_NGAY_SINHParameter, v_THANG_SINHParameter, v_NAM_SINHParameter, v_GIOI_TINHParameter, v_DIA_CHIParameter, v_NGAY_THAM_GIAParameter, v_MA_KHU_PHOParameter);
        }
    
        public virtual int SP_THANH_VIEN_THAM_GIA_HD_DELETE(Nullable<decimal> v_MA_HOAT_DONG, Nullable<decimal> v_MA_THANH_VIEN)
        {
            var v_MA_HOAT_DONGParameter = v_MA_HOAT_DONG.HasValue ?
                new ObjectParameter("V_MA_HOAT_DONG", v_MA_HOAT_DONG) :
                new ObjectParameter("V_MA_HOAT_DONG", typeof(decimal));
    
            var v_MA_THANH_VIENParameter = v_MA_THANH_VIEN.HasValue ?
                new ObjectParameter("V_MA_THANH_VIEN", v_MA_THANH_VIEN) :
                new ObjectParameter("V_MA_THANH_VIEN", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_THANH_VIEN_THAM_GIA_HD_DELETE", v_MA_HOAT_DONGParameter, v_MA_THANH_VIENParameter);
        }
    
        public virtual int SP_THANH_VIEN_THAM_GIA_HD_INSERT(Nullable<decimal> v_MA_HOAT_DONG, Nullable<decimal> v_MA_THANH_VIEN)
        {
            var v_MA_HOAT_DONGParameter = v_MA_HOAT_DONG.HasValue ?
                new ObjectParameter("V_MA_HOAT_DONG", v_MA_HOAT_DONG) :
                new ObjectParameter("V_MA_HOAT_DONG", typeof(decimal));
    
            var v_MA_THANH_VIENParameter = v_MA_THANH_VIEN.HasValue ?
                new ObjectParameter("V_MA_THANH_VIEN", v_MA_THANH_VIEN) :
                new ObjectParameter("V_MA_THANH_VIEN", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_THANH_VIEN_THAM_GIA_HD_INSERT", v_MA_HOAT_DONGParameter, v_MA_THANH_VIENParameter);
        }
    
        public virtual int SP_THANH_VIEN_UPDATE(Nullable<decimal> v_MA_THANH_VIEN, string v_HO, string v_TEN, Nullable<decimal> v_NGAY_SINH, Nullable<decimal> v_THANG_SINH, Nullable<decimal> v_NAM_SINH, string v_GIOI_TINH, string v_DIA_CHI, Nullable<decimal> v_MA_KHU_PHO)
        {
            var v_MA_THANH_VIENParameter = v_MA_THANH_VIEN.HasValue ?
                new ObjectParameter("V_MA_THANH_VIEN", v_MA_THANH_VIEN) :
                new ObjectParameter("V_MA_THANH_VIEN", typeof(decimal));
    
            var v_HOParameter = v_HO != null ?
                new ObjectParameter("V_HO", v_HO) :
                new ObjectParameter("V_HO", typeof(string));
    
            var v_TENParameter = v_TEN != null ?
                new ObjectParameter("V_TEN", v_TEN) :
                new ObjectParameter("V_TEN", typeof(string));
    
            var v_NGAY_SINHParameter = v_NGAY_SINH.HasValue ?
                new ObjectParameter("V_NGAY_SINH", v_NGAY_SINH) :
                new ObjectParameter("V_NGAY_SINH", typeof(decimal));
    
            var v_THANG_SINHParameter = v_THANG_SINH.HasValue ?
                new ObjectParameter("V_THANG_SINH", v_THANG_SINH) :
                new ObjectParameter("V_THANG_SINH", typeof(decimal));
    
            var v_NAM_SINHParameter = v_NAM_SINH.HasValue ?
                new ObjectParameter("V_NAM_SINH", v_NAM_SINH) :
                new ObjectParameter("V_NAM_SINH", typeof(decimal));
    
            var v_GIOI_TINHParameter = v_GIOI_TINH != null ?
                new ObjectParameter("V_GIOI_TINH", v_GIOI_TINH) :
                new ObjectParameter("V_GIOI_TINH", typeof(string));
    
            var v_DIA_CHIParameter = v_DIA_CHI != null ?
                new ObjectParameter("V_DIA_CHI", v_DIA_CHI) :
                new ObjectParameter("V_DIA_CHI", typeof(string));
    
            var v_MA_KHU_PHOParameter = v_MA_KHU_PHO.HasValue ?
                new ObjectParameter("V_MA_KHU_PHO", v_MA_KHU_PHO) :
                new ObjectParameter("V_MA_KHU_PHO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_THANH_VIEN_UPDATE", v_MA_THANH_VIENParameter, v_HOParameter, v_TENParameter, v_NGAY_SINHParameter, v_THANG_SINHParameter, v_NAM_SINHParameter, v_GIOI_TINHParameter, v_DIA_CHIParameter, v_MA_KHU_PHOParameter);
        }
    
        public virtual int SP_TINHLUONG()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TINHLUONG");
        }
    
        public virtual int SP_TV_BAN_CHAP_HANH_DELETE(Nullable<decimal> v_MA_BCH)
        {
            var v_MA_BCHParameter = v_MA_BCH.HasValue ?
                new ObjectParameter("V_MA_BCH", v_MA_BCH) :
                new ObjectParameter("V_MA_BCH", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TV_BAN_CHAP_HANH_DELETE", v_MA_BCHParameter);
        }
    
        public virtual int SP_TV_BAN_CHAP_HANH_INSERT(Nullable<decimal> v_MA_BCH, string v_DAN_TOC, string v_TON_GIAO, string v_NGHE_NGHIEP, string v_DON_VI_CONG_TAC, string v_TRINH_DO_HOC_VAN, string v_TRINH_DO_CHUYEN_MON, string v_TRINH_DO_LY_LUAN_CHINH_TRI, string v_USERNAME, string v_PASSWORD, string v_EMAIL, Nullable<decimal> v_MA_CHUC_VU)
        {
            var v_MA_BCHParameter = v_MA_BCH.HasValue ?
                new ObjectParameter("V_MA_BCH", v_MA_BCH) :
                new ObjectParameter("V_MA_BCH", typeof(decimal));
    
            var v_DAN_TOCParameter = v_DAN_TOC != null ?
                new ObjectParameter("V_DAN_TOC", v_DAN_TOC) :
                new ObjectParameter("V_DAN_TOC", typeof(string));
    
            var v_TON_GIAOParameter = v_TON_GIAO != null ?
                new ObjectParameter("V_TON_GIAO", v_TON_GIAO) :
                new ObjectParameter("V_TON_GIAO", typeof(string));
    
            var v_NGHE_NGHIEPParameter = v_NGHE_NGHIEP != null ?
                new ObjectParameter("V_NGHE_NGHIEP", v_NGHE_NGHIEP) :
                new ObjectParameter("V_NGHE_NGHIEP", typeof(string));
    
            var v_DON_VI_CONG_TACParameter = v_DON_VI_CONG_TAC != null ?
                new ObjectParameter("V_DON_VI_CONG_TAC", v_DON_VI_CONG_TAC) :
                new ObjectParameter("V_DON_VI_CONG_TAC", typeof(string));
    
            var v_TRINH_DO_HOC_VANParameter = v_TRINH_DO_HOC_VAN != null ?
                new ObjectParameter("V_TRINH_DO_HOC_VAN", v_TRINH_DO_HOC_VAN) :
                new ObjectParameter("V_TRINH_DO_HOC_VAN", typeof(string));
    
            var v_TRINH_DO_CHUYEN_MONParameter = v_TRINH_DO_CHUYEN_MON != null ?
                new ObjectParameter("V_TRINH_DO_CHUYEN_MON", v_TRINH_DO_CHUYEN_MON) :
                new ObjectParameter("V_TRINH_DO_CHUYEN_MON", typeof(string));
    
            var v_TRINH_DO_LY_LUAN_CHINH_TRIParameter = v_TRINH_DO_LY_LUAN_CHINH_TRI != null ?
                new ObjectParameter("V_TRINH_DO_LY_LUAN_CHINH_TRI", v_TRINH_DO_LY_LUAN_CHINH_TRI) :
                new ObjectParameter("V_TRINH_DO_LY_LUAN_CHINH_TRI", typeof(string));
    
            var v_USERNAMEParameter = v_USERNAME != null ?
                new ObjectParameter("V_USERNAME", v_USERNAME) :
                new ObjectParameter("V_USERNAME", typeof(string));
    
            var v_PASSWORDParameter = v_PASSWORD != null ?
                new ObjectParameter("V_PASSWORD", v_PASSWORD) :
                new ObjectParameter("V_PASSWORD", typeof(string));
    
            var v_EMAILParameter = v_EMAIL != null ?
                new ObjectParameter("V_EMAIL", v_EMAIL) :
                new ObjectParameter("V_EMAIL", typeof(string));
    
            var v_MA_CHUC_VUParameter = v_MA_CHUC_VU.HasValue ?
                new ObjectParameter("V_MA_CHUC_VU", v_MA_CHUC_VU) :
                new ObjectParameter("V_MA_CHUC_VU", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TV_BAN_CHAP_HANH_INSERT", v_MA_BCHParameter, v_DAN_TOCParameter, v_TON_GIAOParameter, v_NGHE_NGHIEPParameter, v_DON_VI_CONG_TACParameter, v_TRINH_DO_HOC_VANParameter, v_TRINH_DO_CHUYEN_MONParameter, v_TRINH_DO_LY_LUAN_CHINH_TRIParameter, v_USERNAMEParameter, v_PASSWORDParameter, v_EMAILParameter, v_MA_CHUC_VUParameter);
        }
    
        public virtual int SP_TV_BAN_CHAP_HANH_UPDATE(Nullable<decimal> v_MA_BCH, string v_DAN_TOC, string v_TON_GIAO, string v_NGHE_NGHIEP, string v_DON_VI_CONG_TAC, string v_TRINH_DO_HOC_VAN, string v_TRINH_DO_CHUYEN_MON, string v_TRINH_DO_LY_LUAN_CHINH_TRI, Nullable<decimal> v_MA_CHUC_VU)
        {
            var v_MA_BCHParameter = v_MA_BCH.HasValue ?
                new ObjectParameter("V_MA_BCH", v_MA_BCH) :
                new ObjectParameter("V_MA_BCH", typeof(decimal));
    
            var v_DAN_TOCParameter = v_DAN_TOC != null ?
                new ObjectParameter("V_DAN_TOC", v_DAN_TOC) :
                new ObjectParameter("V_DAN_TOC", typeof(string));
    
            var v_TON_GIAOParameter = v_TON_GIAO != null ?
                new ObjectParameter("V_TON_GIAO", v_TON_GIAO) :
                new ObjectParameter("V_TON_GIAO", typeof(string));
    
            var v_NGHE_NGHIEPParameter = v_NGHE_NGHIEP != null ?
                new ObjectParameter("V_NGHE_NGHIEP", v_NGHE_NGHIEP) :
                new ObjectParameter("V_NGHE_NGHIEP", typeof(string));
    
            var v_DON_VI_CONG_TACParameter = v_DON_VI_CONG_TAC != null ?
                new ObjectParameter("V_DON_VI_CONG_TAC", v_DON_VI_CONG_TAC) :
                new ObjectParameter("V_DON_VI_CONG_TAC", typeof(string));
    
            var v_TRINH_DO_HOC_VANParameter = v_TRINH_DO_HOC_VAN != null ?
                new ObjectParameter("V_TRINH_DO_HOC_VAN", v_TRINH_DO_HOC_VAN) :
                new ObjectParameter("V_TRINH_DO_HOC_VAN", typeof(string));
    
            var v_TRINH_DO_CHUYEN_MONParameter = v_TRINH_DO_CHUYEN_MON != null ?
                new ObjectParameter("V_TRINH_DO_CHUYEN_MON", v_TRINH_DO_CHUYEN_MON) :
                new ObjectParameter("V_TRINH_DO_CHUYEN_MON", typeof(string));
    
            var v_TRINH_DO_LY_LUAN_CHINH_TRIParameter = v_TRINH_DO_LY_LUAN_CHINH_TRI != null ?
                new ObjectParameter("V_TRINH_DO_LY_LUAN_CHINH_TRI", v_TRINH_DO_LY_LUAN_CHINH_TRI) :
                new ObjectParameter("V_TRINH_DO_LY_LUAN_CHINH_TRI", typeof(string));
    
            var v_MA_CHUC_VUParameter = v_MA_CHUC_VU.HasValue ?
                new ObjectParameter("V_MA_CHUC_VU", v_MA_CHUC_VU) :
                new ObjectParameter("V_MA_CHUC_VU", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TV_BAN_CHAP_HANH_UPDATE", v_MA_BCHParameter, v_DAN_TOCParameter, v_TON_GIAOParameter, v_NGHE_NGHIEPParameter, v_DON_VI_CONG_TACParameter, v_TRINH_DO_HOC_VANParameter, v_TRINH_DO_CHUYEN_MONParameter, v_TRINH_DO_LY_LUAN_CHINH_TRIParameter, v_MA_CHUC_VUParameter);
        }
    
        public virtual int SP_CHECKLOGIN(string v_USERNAME, string v_PASSWORD, ObjectParameter v_LOGGEDIN)
        {
            var v_USERNAMEParameter = v_USERNAME != null ?
                new ObjectParameter("V_USERNAME", v_USERNAME) :
                new ObjectParameter("V_USERNAME", typeof(string));
    
            var v_PASSWORDParameter = v_PASSWORD != null ?
                new ObjectParameter("V_PASSWORD", v_PASSWORD) :
                new ObjectParameter("V_PASSWORD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CHECKLOGIN", v_USERNAMEParameter, v_PASSWORDParameter, v_LOGGEDIN);
        }
    }
}
