//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHoiNguoiCaoTuoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEU_CHI
    {
        public decimal MA_PHIEU_CHI { get; set; }
        public System.DateTime NGAY_LAP_PHIEU_CHI { get; set; }
        public string NOI_DUNG_CHI { get; set; }
        public decimal SO_TIEN_CHI { get; set; }
        public string DA_DUYET { get; set; }
        public Nullable<System.DateTime> NGAY_DUYET { get; set; }
        public Nullable<decimal> MA_HOAT_DONG { get; set; }
        public decimal MA_BCH { get; set; }
    
        public virtual HOAT_DONG HOAT_DONG { get; set; }
        public virtual TV_BAN_CHAP_HANH TV_BAN_CHAP_HANH { get; set; }
    }
}
