//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHoiNguoiCaoTuoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANH_VIEN_CLB
    {
        public decimal MA_CLB { get; set; }
        public decimal MA_THANH_VIEN { get; set; }
        public System.DateTime NGAY_THAM_GIA_CLB { get; set; }
    
        public virtual CLB CLB { get; set; }
        public virtual THANH_VIEN THANH_VIEN { get; set; }
    }
}
