//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHoiNguoiCaoTuoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CHI_TIET_HOP_BCH
    {
        public decimal MA_CUOC_HOP_BCH { get; set; }
        public System.DateTime NGAY_GIO_HOP { get; set; }
        public decimal MA_BCH { get; set; }
        public string HOTEN { get; set; }
    }
}
