//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHoiNguoiCaoTuoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CHUC_VU
    {
        public decimal MA_CHUC_VU { get; set; }
        public string TEN_CHUC_VU { get; set; }
        public decimal HE_SO_LUONG { get; set; }
    }
}
