//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHoiNguoiCaoTuoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_HOAT_DONG
    {
        public decimal MA_HOAT_DONG { get; set; }
        public string NOI_DUNG_HOAT_DONG { get; set; }
        public System.DateTime NGAY_BAT_DAU { get; set; }
        public System.DateTime NGAY_KET_THUC { get; set; }
        public byte DIEM_TOI_DA { get; set; }
        public Nullable<byte> DIEM_DAT_DUOC { get; set; }
    }
}
