//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHoiNguoiCaoTuoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_HOP_THUONG_NIEN
    {
        public decimal MA_CUOC_HOP_TN { get; set; }
        public System.DateTime NGAY_GIO_HOP { get; set; }
        public string NOI_DUNG_HOP { get; set; }
        public string DIA_DIEM_HOP { get; set; }
    }
}
