//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHoiNguoiCaoTuoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PHIEU_THU
    {
        public decimal MA_PHIEU_THU { get; set; }
        public System.DateTime NGAY_LAP_PHIEU_THU { get; set; }
        public string NOI_DUNG_PHIEU_THU { get; set; }
        public decimal SO_TIEN_THU { get; set; }
        public decimal MA_BCH { get; set; }
        public string HOTENBCH { get; set; }
        public Nullable<decimal> MA_THANH_VIEN { get; set; }
        public string HOTENTV { get; set; }
    }
}
