//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHoiNguoiCaoTuoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_THANH_VIEN
    {
        public decimal MA_THANH_VIEN { get; set; }
        public string HO { get; set; }
        public string TEN { get; set; }
        public Nullable<byte> NGAY_SINH { get; set; }
        public Nullable<byte> THANG_SINH { get; set; }
        public short NAM_SINH { get; set; }
        public string GIOI_TINH { get; set; }
        public string DIA_CHI { get; set; }
        public System.DateTime NGAY_THAM_GIA { get; set; }
        public decimal MA_KHU_PHO { get; set; }
        public string TEN_KHU_PHO { get; set; }
    }
}
