//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHoiNguoiCaoTuoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TV_BAN_CHAP_HANH
    {
        public decimal MA_BCH { get; set; }
        public string HO { get; set; }
        public string TEN { get; set; }
        public string DAN_TOC { get; set; }
        public string TON_GIAO { get; set; }
        public string NGHE_NGHIEP { get; set; }
        public string DON_VI_CONG_TAC { get; set; }
        public string TRINH_DO_HOC_VAN { get; set; }
        public string TRINH_DO_CHUYEN_MON { get; set; }
        public string TRINH_DO_LY_LUAN_CHINH_TRI { get; set; }
        public decimal LUONG { get; set; }
        public decimal MA_CHUC_VU { get; set; }
        public string TEN_CHUC_VU { get; set; }
    }
}
